name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cargo
        uses: dtolnay/rust-toolchain@stable
      
      - name: Update Cargo
        run: rustup update stable

      - name: Install Sui CLI
        run: cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui --features tracing

      - name: Verify Sui installation
        run: sui --version

      - name: Run Move tests
        run: sui move test