name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Sui CLI
        run: |
          curl -fsSL https://install.sui.io | sh
          echo "$HOME/.sui/bin" >> $GITHUB_PATH

      - name: Verify Sui installation
        run: sui --version

      - name: Run Move tests
        run: sui move test